#############################################################################
# Makefile for building: BrowBeater.app/Contents/MacOS/BrowBeater
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  BrowBeater.pro
# Template: app
# Command: /Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/bin/qmake -o Makefile BrowBeater.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers -I../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang -F/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib
QMAKE         = /Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BrowBeater1.0.0
DISTDIR = /Users/earlye/src/whispersoft/BrowBeater/.tmp/BrowBeater1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib -framework AppKit -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		wmainwindow.cpp \
		wbrowserbutton.cpp \
		osx.mm moc_wmainwindow.cpp \
		moc_wbrowserbutton.cpp
OBJECTS       = main.o \
		wmainwindow.o \
		wbrowserbutton.o \
		osx.o \
		moc_wmainwindow.o \
		moc_wbrowserbutton.o
DIST          = ../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/uic.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		BrowBeater.pro wmainwindow.h \
		wbrowserbutton.h \
		BrowserRegistrar.hpp main.cpp \
		wmainwindow.cpp \
		wbrowserbutton.cpp \
		osx.mm
QMAKE_TARGET  = BrowBeater
DESTDIR       = 
TARGET        = BrowBeater.app/Contents/MacOS/BrowBeater


first: all
####### Build rules

$(TARGET): ui_wmainwindow.h $(OBJECTS)  
	@test -d BrowBeater.app/Contents/MacOS/ || mkdir -p BrowBeater.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BrowBeater.pro ../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf ../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/uic.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		BrowBeater.pro \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile BrowBeater.pro
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/qdevice.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/device_config.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/unix.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/mac.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/macx.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/clang.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/qconfig.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/default_post.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/qt.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/resources.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/moc.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/uic.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/yacc.prf:
../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/features/lex.prf:
BrowBeater.pro:
../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BrowBeater.pro

qmake_all: FORCE

BrowBeater.app/Contents/PkgInfo: 
	@test -d BrowBeater.app/Contents || mkdir -p BrowBeater.app/Contents
	@$(DEL_FILE) BrowBeater.app/Contents/PkgInfo
	@echo "APPL????" > BrowBeater.app/Contents/PkgInfo
BrowBeater.app/Contents/Resources/empty.lproj: 
	@test -d BrowBeater.app/Contents/Resources || mkdir -p BrowBeater.app/Contents/Resources
	@touch BrowBeater.app/Contents/Resources/empty.lproj
	
BrowBeater.app/Contents/Info.plist: 
	@test -d BrowBeater.app/Contents || mkdir -p BrowBeater.app/Contents
	@$(DEL_FILE) BrowBeater.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.BrowBeater,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,BrowBeater,g" -e "s,@LIBRARY@,BrowBeater,g" -e "s,@TYPEINFO@,????,g" ../../../Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >BrowBeater.app/Contents/Info.plist

all: Makefile \
		BrowBeater.app/Contents/PkgInfo \
		BrowBeater.app/Contents/Resources/empty.lproj \
		BrowBeater.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents wmainwindow.h wbrowserbutton.h BrowserRegistrar.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp wmainwindow.cpp wbrowserbutton.cpp osx.mm $(DISTDIR)/
	$(COPY_FILE) --parents osx.mm $(DISTDIR)/
	$(COPY_FILE) --parents wmainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r BrowBeater.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_wmainwindow.cpp moc_wbrowserbutton.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_wmainwindow.cpp moc_wbrowserbutton.cpp
moc_wmainwindow.cpp: ../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		BrowserRegistrar.hpp \
		wmainwindow.h
	/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang -I/Users/earlye/src/whispersoft/BrowBeater -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib wmainwindow.h -o moc_wmainwindow.cpp

moc_wbrowserbutton.cpp: BrowserRegistrar.hpp \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		wbrowserbutton.h
	/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/mkspecs/macx-clang -I/Users/earlye/src/whispersoft/BrowBeater -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/lib wbrowserbutton.h -o moc_wbrowserbutton.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_wmainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_wmainwindow.h
ui_wmainwindow.h: wmainwindow.ui
	/Users/earlye/Applications/Qt/5.6.0/5.6/clang_64/bin/uic wmainwindow.ui -o ui_wmainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp wmainwindow.h \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		BrowserRegistrar.hpp \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

wmainwindow.o: wmainwindow.cpp wmainwindow.h \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		BrowserRegistrar.hpp \
		ui_wmainwindow.h \
		wbrowserbutton.h \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wmainwindow.o wmainwindow.cpp

wbrowserbutton.o: wbrowserbutton.cpp wbrowserbutton.h \
		BrowserRegistrar.hpp \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Applications/Qt/5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wbrowserbutton.o wbrowserbutton.cpp

osx.o: osx.mm BrowserRegistrar.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o osx.o osx.mm

moc_wmainwindow.o: moc_wmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wmainwindow.o moc_wmainwindow.cpp

moc_wbrowserbutton.o: moc_wbrowserbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wbrowserbutton.o moc_wbrowserbutton.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

